### ISSUE TITLE
DUDe dont give up

### ISSUE THREAD

**Issue by kalebplayz125** [lem6ns/NitroPerks#29]
i use this plugin all the time please dont abandon it

**Comment by MrIDontKNow-hub** [comment]
I agree with him, please dont give up = (

**Comment by dav1312** [comment]
@kalebplayz125 @MrIDontKNow-hub The issue is not "giving up"
Spoofing data to discord using the screenshare bypass can result in your account getting banned

**Comment by lem6ns** [comment]
^
